name: こんにちはワークフロー

on:
  workflow_dispatch:  # 手動実行を可能にする
  push:               # プッシュ時に実行
  pull_request:       # プルリクエスト時に実行

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
    - name: こんにちは！を出力
      run: echo "こんにちは！"
